// src/enums/errors.ts

export enum Errors {
  LATEX_COMPILATION_FAILED = "LATEX_COMPILATION_FAILED",
  LATEX_TEMP_DIR_CREATION_FAILED = "LATEX_TEMP_DIR_CREATION_FAILED",
  LATEX_FILE_WRITE_FAILED = "LATEX_FILE_WRITE_FAILED",
  LATEX_PDF_READ_FAILED = "LATEX_PDF_READ_FAILED",
  LATEX_TIMEOUT_EXCEEDED = "LATEX_TIMEOUT_EXCEEDED",
  LATEX_CLEANUP_FAILED = "LATEX_CLEANUP_FAILED",
  LATEX_INVALID_ZIP = "LATEX_INVALID_ZIP",
  LATEX_UNSAFE_FILE = "LATEX_UNSAFE_FILE",
  LATEX_ENTRY_FILE_NOT_FOUND = "LATEX_ENTRY_FILE_NOT_FOUND",
  LATEX_ZIP_EXTRACTION_FAILED = "LATEX_ZIP_EXTRACTION_FAILED",
}
